version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dockerYnov
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: dockerYnov
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://backend:3000
    depends_on:
      - backend
    networks:
      - mynetwork
    ports:
      - "80:80"

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
